export const QuestionTypes = {
    SINGLE_SELECT_QUESTION: "SINGLE_SELECT_QUESTION",
    MULTIPLE_SELECT_QUESTION: "MULTIPLE_SELECT_QUESTION",
    WRITING_QUESTION: "WRITING_QUESTION",
    ORDER_QUESTION: 3,
}